// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/conf_test_list_and_dict.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UF.Config {

  /// <summary>Holder for reflection information generated from client/conf_test_list_and_dict.proto</summary>
  public static partial class ConfTestListAndDictReflection {

    #region Descriptor
    /// <summary>File descriptor for client/conf_test_list_and_dict.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfTestListAndDictReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRjbGllbnQvY29uZl90ZXN0X2xpc3RfYW5kX2RpY3QucHJvdG8SBmNsaWVu",
            "dBoZY29tbW9uL2VudW1fbW9kdWxlcy5wcm90byK3AgoTQ29uZlRlc3RMaXN0",
            "QW5kRGljdBINCgVzdGFycxgBIAMoCRIOCgZsZXZlbHMYAiADKAUSNQoFbmFt",
            "ZXMYAyADKAsyJi5jbGllbnQuQ29uZlRlc3RMaXN0QW5kRGljdC5OYW1lc0Vu",
            "dHJ5EjcKBmhlcm9lcxgEIAMoCzInLmNsaWVudC5Db25mVGVzdExpc3RBbmRE",
            "aWN0Lkhlcm9lc0VudHJ5EhMKC2xpc3RvZkhlcm9zGAUgAygFEh8KBm1vZHVs",
            "ZRgGIAEoDjIPLmNvbW1vbi5Nb2R1bGVzGiwKCk5hbWVzRW50cnkSCwoDa2V5",
            "GAEgASgNEg0KBXZhbHVlGAIgASgJOgI4ARotCgtIZXJvZXNFbnRyeRILCgNr",
            "ZXkYASABKAkSDQoFdmFsdWUYAiABKAU6AjgBQgyqAglVRi5Db25maWdiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::UF.Config.EnumModulesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::UF.Config.ConfTestListAndDict), global::UF.Config.ConfTestListAndDict.Parser, new[]{ "Stars", "Levels", "Names", "Heroes", "ListofHeros", "Module" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfTestListAndDict : pb::IMessage<ConfTestListAndDict> {
    private static readonly pb::MessageParser<ConfTestListAndDict> _parser = new pb::MessageParser<ConfTestListAndDict>(() => new ConfTestListAndDict());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfTestListAndDict> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UF.Config.ConfTestListAndDictReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfTestListAndDict() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfTestListAndDict(ConfTestListAndDict other) : this() {
      stars_ = other.stars_.Clone();
      levels_ = other.levels_.Clone();
      names_ = other.names_.Clone();
      heroes_ = other.heroes_.Clone();
      listofHeros_ = other.listofHeros_.Clone();
      module_ = other.module_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfTestListAndDict Clone() {
      return new ConfTestListAndDict(this);
    }

    /// <summary>Field number for the "stars" field.</summary>
    public const int StarsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_stars_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> stars_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Stars {
      get { return stars_; }
    }

    /// <summary>Field number for the "levels" field.</summary>
    public const int LevelsFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_levels_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> levels_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Levels {
      get { return levels_; }
    }

    /// <summary>Field number for the "names" field.</summary>
    public const int NamesFieldNumber = 3;
    private static readonly pbc::MapField<uint, string>.Codec _map_names_codec
        = new pbc::MapField<uint, string>.Codec(pb::FieldCodec.ForUInt32(8), pb::FieldCodec.ForString(18), 26);
    private readonly pbc::MapField<uint, string> names_ = new pbc::MapField<uint, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<uint, string> Names {
      get { return names_; }
    }

    /// <summary>Field number for the "heroes" field.</summary>
    public const int HeroesFieldNumber = 4;
    private static readonly pbc::MapField<string, int>.Codec _map_heroes_codec
        = new pbc::MapField<string, int>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForInt32(16), 34);
    private readonly pbc::MapField<string, int> heroes_ = new pbc::MapField<string, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, int> Heroes {
      get { return heroes_; }
    }

    /// <summary>Field number for the "listofHeros" field.</summary>
    public const int ListofHerosFieldNumber = 5;
    private static readonly pb::FieldCodec<int> _repeated_listofHeros_codec
        = pb::FieldCodec.ForInt32(42);
    private readonly pbc::RepeatedField<int> listofHeros_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> ListofHeros {
      get { return listofHeros_; }
    }

    /// <summary>Field number for the "module" field.</summary>
    public const int ModuleFieldNumber = 6;
    private global::UF.Config.Modules module_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::UF.Config.Modules Module {
      get { return module_; }
      set {
        module_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfTestListAndDict);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfTestListAndDict other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!stars_.Equals(other.stars_)) return false;
      if(!levels_.Equals(other.levels_)) return false;
      if (!Names.Equals(other.Names)) return false;
      if (!Heroes.Equals(other.Heroes)) return false;
      if(!listofHeros_.Equals(other.listofHeros_)) return false;
      if (Module != other.Module) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= stars_.GetHashCode();
      hash ^= levels_.GetHashCode();
      hash ^= Names.GetHashCode();
      hash ^= Heroes.GetHashCode();
      hash ^= listofHeros_.GetHashCode();
      if (Module != 0) hash ^= Module.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      stars_.WriteTo(output, _repeated_stars_codec);
      levels_.WriteTo(output, _repeated_levels_codec);
      names_.WriteTo(output, _map_names_codec);
      heroes_.WriteTo(output, _map_heroes_codec);
      listofHeros_.WriteTo(output, _repeated_listofHeros_codec);
      if (Module != 0) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Module);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += stars_.CalculateSize(_repeated_stars_codec);
      size += levels_.CalculateSize(_repeated_levels_codec);
      size += names_.CalculateSize(_map_names_codec);
      size += heroes_.CalculateSize(_map_heroes_codec);
      size += listofHeros_.CalculateSize(_repeated_listofHeros_codec);
      if (Module != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Module);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfTestListAndDict other) {
      if (other == null) {
        return;
      }
      stars_.Add(other.stars_);
      levels_.Add(other.levels_);
      names_.Add(other.names_);
      heroes_.Add(other.heroes_);
      listofHeros_.Add(other.listofHeros_);
      if (other.Module != 0) {
        Module = other.Module;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            stars_.AddEntriesFrom(input, _repeated_stars_codec);
            break;
          }
          case 18:
          case 16: {
            levels_.AddEntriesFrom(input, _repeated_levels_codec);
            break;
          }
          case 26: {
            names_.AddEntriesFrom(input, _map_names_codec);
            break;
          }
          case 34: {
            heroes_.AddEntriesFrom(input, _map_heroes_codec);
            break;
          }
          case 42:
          case 40: {
            listofHeros_.AddEntriesFrom(input, _repeated_listofHeros_codec);
            break;
          }
          case 48: {
            module_ = (global::UF.Config.Modules) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
