// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/enum_modules.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UF.Config {

  /// <summary>Holder for reflection information generated from common/enum_modules.proto</summary>
  public static partial class EnumModulesReflection {

    #region Descriptor
    /// <summary>File descriptor for common/enum_modules.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumModulesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chljb21tb24vZW51bV9tb2R1bGVzLnByb3RvEgZjb21tb24qRQoHTW9kdWxl",
            "cxINCglNT0RVTEVTXzEQABINCglNT0RVTEVTXzIQARINCglNT0RVTEVTXzMQ",
            "AhINCglNT0RVTEVTXzQQA0IMqgIJVUYuQ29uZmlnYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::UF.Config.Modules), }, null));
    }
    #endregion

  }
  #region Enums
  public enum Modules {
    [pbr::OriginalName("MODULES_1")] _1 = 0,
    [pbr::OriginalName("MODULES_2")] _2 = 1,
    [pbr::OriginalName("MODULES_3")] _3 = 2,
    [pbr::OriginalName("MODULES_4")] _4 = 3,
  }

  #endregion

}

#endregion Designer generated code
