/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qiong_mylib_libuu_UUHelper */

#ifndef _Included_qiong_mylib_libuu_UUHelper
#define _Included_qiong_mylib_libuu_UUHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qiong_mylib_libuu_UUHelper
 * Method:    setAssetManager
 * Signature: (Landroid/content/res/AssetManager;)V
 */
JNIEXPORT void JNICALL Java_qiong_mylib_libuu_UUHelper_setAssetManager
  (JNIEnv *, jclass, jobject);

/*
 * Class:     qiong_mylib_libuu_UUHelper
 * Method:    newObbFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_qiong_mylib_libuu_UUHelper_newObbFile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
